### PR TITLE
update for easybuild 3.5.1; fixes/improvements

### PR DESCRIPTION
**Pull request by michaelkarlcoleman**
Switch to EasyBuild 3.5.1.  Add some missing rpm's that the current
easyconfigs assume will be present.  Also add a few that are handy for
development and debugging.

(Your configs are incredibly handy, BTW!)

### CODE REVIEW

**Comment by pescobar** [comment]
hi @tutufan 

Thanks for you contribution and sorry for the late reply, I have been traveling a lot lately.

This PR conflicts with the existing files. Would you mind renaming your file `centos-7-easybuild-3.5.1.bootstrap` to something like  `centos-7-easybuild-3.5.1-devel.bootstrap`? (or any other name that you prefer?) 

This way we can have a singularity file for production deployments which doesn't require all the devel and debugging tools (and should be smaller) and a devel version with more tools

**Comment by michaelkarlcoleman** [comment]
Hi @pescobar, I've rebased this PR onto the current HEAD.  Note that most of these changes are required for all cases.  These introduced rpms that are osdependencies of easyconfigs--sometimes explicit and sometimes implicit (and some of these cause rather obscure errors).  The equivalent changes should probably be made for all of the `.bootstrap` files, but I'm only using the latest one.

There are three items that are to aid in debugging only: `emacs`, `strace`, and `pycodestyle`.  I hope that you will consider including these in the "production" image as well.  There is little more maddening than trying to debug an issue and discovering that the necessary tools are not at hand.  The savings in size seems minimal.

In any case, thanks for providing this.  It's a brilliant idea, and I'm making great use of it.

**Comment by pescobar** [comment]
hi @tutufan 

I agree with you. Including those packages seems quite convenient and the size increase is quite small.  The only reason why I was tempted to reject the PR is because it includes emacs ;)

Thanks for the contribution!

**Comment by michaelkarlcoleman** [comment]
Awesome--Thanks @pescobar !

**Pull request merged**
